# MangoHud — SHIFT+F12 liga/desliga | ativar: MANGOHUD=1 %command% (Steam)
toggle_hud=Shift_R+F12
position=top-left
font_size=18
background_alpha=0.4
round_corners=6

fps
frametime
frame_timing
gpu_stats
gpu_temp
cpu_stats
cpu_temp
ram
vram
gamemode
